name: Zip Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Necessary permission to create releases and upload assets

jobs:
  zip_and_release:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      ZIP_NAME: ${{ github.repository_owner }}-${{ github.event.repository.name }}.zip

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create zip archive
      shell: bash
      run: |
        echo "Organization Name: $ORG_NAME"
        echo "Repository Name: $REPO_NAME"
        echo "Zip File Name: $ZIP_NAME"

        # Exclude .py files and other specified patterns
        zip -r "$ZIP_NAME" ./* -x "*.py" -x "path/to/exclude/*" -x "*.md"

    - name: Create Release and Upload Zip
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ github.run_number }}
        releaseName: "Release v${{ github.run_number }}"
        artifacts: ${{ env.ZIP_NAME }}
        artifactContentType: application/zip
        draft: false
        prerelease: false